awc_site/accounts/urls.py
from django.urls import path, include
from accounts import views


app_name = 'accounts'

urlpatterns = [
	path('sign_up/', views.sign_up, name='sign_up'),
	path('login/', views.login, name='login'),
	path('logout/', views.logout, name='logout'),
]

awc_site/awc_site/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views


urlpatterns = [
    path('', accounts.views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('space/', include('space.urls')),
]


awc_site/space/urls.py
from django.urls import path, include
from space import views


app_name = 'space'

urlpatterns = [
    path('', views.space_list, name='space_list'),                              # 개설된 모든 Public 공간 리스트
    path('search_space/', views.search_space_list, name='search_space_list'),   # 검색한 공간 리스트
    path('create_space/', views.create_space, name='create_space'),             # 공간 생성
    path('<space_name>/write_post/', views.write_post, name='write_post'),      # 공간 안에서 글쓰기
    path('<space_name>/', views.show_space, name='show_space'),                 # 공간 메인 페이지
    path('<space_name>/<int:post_id>/', views.post_detail, name='post_detail'), # 공간 내의 게시글
    path('search_name', views.search_name, name='search_name'),
    path('information', views.information, name='information'),
]

awc_site/templates/base.html
<!DOCTYPE html>
<html lang="kr">
<head>
    {% load static %}
    {% load svg %}
    <title>{%  block title %}{% endblock %}</title>

    <title>Bootstrap 4 Website Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- import s3 API -->
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.283.1.min.js"></script>
    <script src="https://awcjs.s3.ap-northeast-2.amazonaws.com/app01.js"></script>
    <!-- import summernote -->
    <!-- -->
    <style>
        .fakeimg {
            height: 200px;
            background: #aaa;
        }
        .icon{
            width: 20px;
            height: 20px;
            background-size: cover;
            display: inline-block;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href="{% url 'index' %}">AWC</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#"></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"></a>
            </li>
        </ul>
    </div>
    <div id="end" class="flexbox">
        {% if user.is_authenticated %}<!--로그인 성공시 if문 -->

        <i class="icon">{% svg 'home' %}</i><a>&nbsp;</a>
        <a href="{% url 'accounts:sign_up' %}" style="color:white">{{user.get_username}}'s list&nbsp;&nbsp;&nbsp;</a>
        <i class="icon" style="background-color:white">{% svg 'logout' %}</i><a>&nbsp;&nbsp;</a>
        <a href="{% url 'accounts:logout' %}" style="color:white">Logout</a>

    </div>
    {% else %}
    <!--로그인 안했을때 else문  -->
    <div id="end" class="flexbox">

        <i class="icon">{% svg 'person' %}</i><a>&nbsp;</a>
        <a href="{% url 'accounts:sign_up' %}" style="color:white">Sign Up&nbsp;&nbsp;&nbsp;</a>
        <i class="icon">{% svg 'login' %}</i><a>&nbsp;&nbsp;</a>
        <a href="{% url 'accounts:login' %}" style="color:white">Login</a>
    </div>
    {% endif %}

</nav>
{% block content %}

{% endblock %}
</body>
</html>

awc_site/templates/main.bak.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'base.html' %}
    {% load static %}
    {% load svg %}
    <title>{%  block title %}-main{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<body>
{% block content%}
<style>
        .carousel-inner > .item {
            width: 100%;
        }
    </style>
<div class="container mt-3">
    <div id="demo" class="carousel slide" data-ride="carousel">
        <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
        </ul>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="jumbotron">
                    <h1>나만의 커뮤니티를 만들어보세요.</h1>
                    <p>- 커뮤니티는 회원만 생성할 수 있습니다.</p><br><br>
                    <i class="icon" style="padding: 10px 55px 10px 100px;">{% svg 'magnifying' %}</i>
                    <a href="#" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-search"></span> 커뮤니티 검색</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'space:create_space' %}" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-plus"></span> 커뮤니티 생성</a>
                    {% endif %}
                </div>
            </div>
            <div class="carousel-item">
                <div class="jumbotron">
                    <h1>나만의 커뮤니티를 만들어보세요.</h1>
                    <p>- 커뮤니티는 회원만 생성할 수 있습니다.</p><br><br>
                    <a href="#" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-search"></span> 커뮤니티 검색</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'space:create_space' %}" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-plus"></span> 커뮤니티 생성</a>
                    {% endif %}
                </div>
            </div>
            <div class="carousel-item">
                <div class="jumbotron">
                    <h1>나만의 커뮤니티를 만들어보세요.</h1>
                    <p>- 커뮤니티는 회원만 생성할 수 있습니다.</p><br><br>
                    <a href="#" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-search"></span> 커뮤니티 검색</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'space:create_space' %}" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-plus"></span> 커뮤니티 생성</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</div>
<!-- 여기가 새로만든 것들 -->
<a href="{% url 'space:space_list' %}" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-search"></span> 커뮤니티 목록(구현완료)</a>
<form action="{% url 'space:search_space_list' %}" method="get">
    <select name="search_option">
        <option value="space_name">공간이름으로 검색</option>
        <option value="space_category">공간 카테고리로 검색</option>
    </select>
    <input type="text" name="q" value="{{ q }}">
    <input type="submit" value="공간 검색">
</form>
<!-- ---------------------- -->
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <p>1번</p>
            <p style="text-align: center;">
                <img src="{% static 'main/locked-padlock.png' %}" alt="">
            </p>
            <p>
                비밀번호, 파일과 같은 중요 정보들은 암호화되어 저장됩니다.
            </p>
        </div>
        <div class="col-md-3">
            <p>2번</p>
            <p style="text-align: center;">
                <img src="{% static 'main/locked-padlock.png' %}" alt="">
            </p>
            <p>
                첨부파일은 인공지능이 검사하므로, 안심하고 다운로드하세요.
            </p>
        </div>
        <div class="col-md-3">
            <p>3번</p>
            <p style="text-align: center;">
                <img src="{% static 'main/locked-padlock.png' %}" alt="">
            </p>
            <p>
                링크 하나로 쉽게 커뮤니티 공간에 입장할 수 있습니다.
            </p>
        </div>
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li class="active"><a href="#">Bookmark</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Menu 1 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Submenu 1-1</a></li>
                        <li><a href="#">Submenu 1-2</a></li>
                        <li><a href="#">Submenu 1-3</a></li>
                    </ul>
                </li>
                <li><a href="https://www.naver.com">naver</a></li>
                <li><a href="#">Menu 3</a></li>
            </ul>
        </div>
        <div class="clearfix visible-lg"></div>
    </div>
</div>

<script>
        $(document).ready(function(){
            // Activate Carousel
            $("#myCarousel").carousel();

            // Enable Carousel Indicators
            $(".item1").click(function(){
                $("#myCarousel").carousel(0);
            });
            $(".item2").click(function(){
                $("#myCarousel").carousel(1);
            });
            $(".item3").click(function(){
                $("#myCarousel").carousel(2);
            });

            // Enable Carousel Controls
            $(".carousel-control-prev").click(function(){
                $("#myCarousel").carousel("prev");
            });
            $(".carousel-control-next").click(function(){
                $("#myCarousel").carousel("next");
            });
        });
    </script>

{% endblock %}
</body>
</html>

awc_site/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'base.html' %}
    {% load static %}
    {% load svg %}
    <title>{%  block title %}-main{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<body>
{% block content%}
<style>
        .carousel-inner > .item {
            width: 100%;
        }
        .carousel-item {
            width: 100%;
            height: 350px;
        }
    </style>
<div class="container mt-3">
    <div id="demo" class="carousel slide" data-ride="carousel" data-interval="4000">
        <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
        </ul>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="jumbotron" >
                    <h1>나만의 커뮤니티를 만들어보세요.</h1>
                    <p>- 커뮤니티는 회원만 생성할 수 있습니다.</p><br><br>
                    <a href="{% url 'space:space_list'  %}" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-search"></span> 커뮤니티 목록</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'space:create_space' %}" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-plus"></span> 커뮤니티 생성</a>
                    {% endif %}
                </div>
            </div>
            <div class="carousel-item">
		    <img src="/static/main/main_2.png" style="width:100%">
            </div>
        </div>
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</div>

<div class="container">
    <h2>검색할 메뉴를 선택해주세요</h2>
    <br>
    <form action="{% url 'space:search_space_list' %}" method="get">
        <select name="search_option">
            <option value="space_name">공간이름으로 검색</option>
            <option value="space_category">공간 카테고리로 검색</option>
        </select>
        <input type="text" name="q" value="{{ q }}">
        <input type="submit" value="공간 검색">
    </form>
    <br>
    <iframe id ="test" width="1200" height="360" frameborder="0" src="{% url 'space:information' %}"></iframe>
</div>
<div class="clearfix visible-lg"></div>
</div>


<script>
        $(document).ready(function(){
            // Activate Carousel
            $("#myCarousel").carousel({interval: 3000});
            // Enable Carousel Indicators
            $(".item1").click(function(){
                $("#myCarousel").carousel(0);
            });
            $(".item2").click(function(){
                $("#myCarousel").carousel(1);
            });
            $(".item3").click(function(){
                $("#myCarousel").carousel(2);
            });

            // Enable Carousel Controls
            $(".carousel-control-prev").click(function(){
                $("#myCarousel").carousel("prev");
            });
            $(".carousel-control-next").click(function(){
                $("#myCarousel").carousel("next");
            });
        });
    </script>

{% endblock %}
</body>
</html>

awc_site/templates/search_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title> {% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>
<body>

<div class="btn-group btn-group-justified">
      <a class="btn btn-primary">Information</a>
  </div>
               {% block content %}

                {% endblock %}

</body>
</html>