awc_site/awc_site/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views


urlpatterns = [
    path('', accounts.views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('space/', include('space.urls')),
]


awc_site/space/urls.py
from django.urls import path, include
from space import views


app_name = 'space'

urlpatterns = [
    path('', views.space_list, name='space_list'),                              # 개설된 모든 Public 공간 리스트
    path('search_space/', views.search_space_list, name='search_space_list'),   # 검색한 공간 리스트
    path('create_space/', views.create_space, name='create_space'),             # 공간 생성
    path('<space_name>/write_post/', views.write_post, name='write_post'),      # 공간 안에서 글쓰기
    path('<space_name>/', views.show_space, name='show_space'),                 # 공간 메인 페이지
    path('<space_name>/<int:post_id>/', views.post_detail, name='post_detail'), # 공간 내의 게시글
    path('search_name', views.search_name, name='search_name'),
    path('information', views.information, name='information'),
]

awc_site/space/models.py
from django.db import models
from django.utils import timezone


# 공간 모델
class Space(models.Model):
    space_access = models.CharField(  # 공간 접근 권한
        max_length=10,
        blank=False,
    )
    space_name = models.CharField(    # 공간 이름
        max_length=35,
        blank=False,
    )
    space_password = models.CharField(  # 공간 비밀번호
        max_length=256,
        blank=False
    )
    space_category = models.CharField(  # 공간 비밀번호
        max_length=256,
        blank=True
    )
    date_created = models.DateTimeField(  # 공간 생성 날짜
        default=timezone.now
    )


# 게시글 모델
class Post(models.Model):
    space = models.ForeignKey(Space, on_delete=models.CASCADE, null=False)   # 공간의 기본키를 외래키로 설정
    writer = models.CharField(max_length=50)
    post_title = models.CharField(max_length=50)
    post_contents = models.TextField(blank=True)
    post_file = models.FileField(blank=True, null=True, unique=False)
    post_date = models.DateTimeField(auto_now_add=True)
    malware_result = models.IntegerField(default=-1)

    class Meta:
        ordering = ['-post_date']

awc_site/space/forms.py
from django import forms
from django.core.validators import RegexValidator
from space.models import Space, Post
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


# 공간(space) 생성 폼
class CreateSpaceForm(forms.ModelForm):

    ACCESS_CHOICES = [('public', 'Public'), ('private', 'Private')]
    # 공간 접근 권한
    space_access = forms.ChoiceField(
        label="생성할 공간의 접근 권한을 선택하세요.",
        choices=ACCESS_CHOICES,
        initial='public',
        widget=forms.RadioSelect(),
        required=True,
    )

    # 공간 이름
    space_name = forms.CharField(
        label="생성할 공간의 이름",
        required=True,
        validators=[
            # 공간 이름 검증
            RegexValidator(
                regex=r"^.{4,30}$",
                message="공간 이름은 최소 4글자 이상, 최대 30글자 이하여야 합니다.",
                code='Invalid'),

            RegexValidator(
                regex=r"^[\w가-힣]+$",
                message="특수문자는 _ 만 사용할 수 있습니다.",
                code='Invalid')
        ]
    )
    # 공간 비밀번호
    space_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'create-space-form',
                'placeholder': '공간 비밀번호',
                'required': 'True'
            }
        ),
        label='공간 비밀번호',
        required=True,
        validators=[
            # 공간 패스워드 검증
            RegexValidator(
                regex=r"^.{4,50}$",
                message="공간 비밀번호는 최소 4자리 이상, 최대 50자리 이하여야 합니다.",
                code='Invalid'),
        ],
    )

    # 공간 비밀번호 확인
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'create-space-form',
                'placeholder': '공간 비밀번호 확인',
                'required': 'True'
            }
        ),
        label='Password confirmation'
    )

    # 공간 카테고리
    space_category = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'create-space-form',
                'placeholder': '카테고리를 입력하세요',
            }
        ),
    )

    class Meta:
        model = Space
        fields = ('space_access', 'space_name', 'space_password', 'confirm_password', 'space_category')

    def clean(self):
        # 패스워드 일치 확인
        cleaned_data = super(CreateSpaceForm, self).clean()
        password = cleaned_data.get('space_password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "입력한 비밀번호가 서로 다릅니다."
            )

        # 공간이름 중복 확인
        space_name = cleaned_data.get('space_name')
        if Space.objects.filter(space_name=space_name).exists():
            raise forms.ValidationError(
                "이미 사용중인 공간 이름입니다."
            )


# 게시글 작성 폼
class WritePostForm(forms.ModelForm):
    
    
    class Meta:
        model = Post
        fields = ('post_title', 'post_contents', 'post_file')
        widgets = {
            'post_contents': SummernoteWidget(),
        }

    # is_valid()로 유효성 검증할 때, 파일은 없어도 되게 설정
    def __init__(self, *args, **kwargs):
        super(WritePostForm, self).__init__(*args, **kwargs)
        self.fields['post_file'].required = False

    # save() 재정의
    def save(self, **kwargs):
        post = super(WritePostForm, self).save(commit=False)
        post.space = kwargs.get('space', None)
        post.writer = kwargs.get('writer', None)
        post.malware_result = kwargs.get('check_result', None)
        post.save()

        return post

awc_site/space/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
# from django.views.generic import ListView
from space.forms import CreateSpaceForm, WritePostForm
from space.models import Space, Post
import time, os
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# 공간 리스트
def space_list(request):
    # 퍼블릭 공간만 모두 가져오기
    spaces = Space.objects.filter(space_access='public')
    post_count = 5
    page = request.GET.get('page')
    paginator = Paginator(spaces, post_count)
    page_count = range(1, paginator.num_pages + 1)  # 이전 1 2 3 4 다음
    try:
        spaces = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        spaces = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        spaces = paginator.page(paginator.num_pages)
    return render(request, 'space/space_list.html', {'spaces': spaces, 'page_count': page_count})


# 검색조건에 부합하는 공간 리스트
def search_space_list(request):
    search_flag = True
    # q값이 없으면 get()의 두번째 인자가 q에 할당된다.
    q = request.GET.get('q', '')

    # 검색 옵션 설정
    search_option = request.GET.get('search_option')
    option = search_option + '__contains'
    # 검색하기
    space = Space.objects.filter(space_access='public')
    post_count = 10
    paginator = Paginator(space, post_count)
    page_count = range(1, paginator.num_pages + 1)  # 이전 1 2 3 4 다음
    if q:
        spaces = Space.objects.filter(**{option: request.GET.get('q')}).order_by('-date_created')

    return render(request, 'space/space_list.html',
                  {'spaces': spaces, 'q': q, 'search_flag': search_flag, 'page_count': page_count})


# 공간 생성
def create_space(request):
    if request.method == 'POST':
        create_space_form = CreateSpaceForm(data=request.POST)

        if create_space_form.is_valid():
            create_space_form.save()
            time.sleep(1)  # s3에 공간이름으로 폴더를 생성하기 위한 시간을 주기 위해, render 전에 1초 대기함.
            return render(request, 'space/create_space_done.html',
                          {'space_name': create_space_form['space_name'].value()})

        else:
            print(create_space_form.errors)

    else:
        create_space_form = CreateSpaceForm()

    return render(request, 'space/create_space.html', {'create_space_form': create_space_form})


'''
# 공간 화면 출력
def show_space(request, space_name):

    # 존재하는 space_name 인지 검사
    space = Space.objects.get(space_name=space_name, space_access='public')

    if space:
        # space에 들어있는 게시글 가져오기
        posts = Post.objects.filter(space_id=space.id)

        return render(request, 'space/show_space.html', {'space': space, 'posts': posts})

    return HttpResponse('존재하지 않는 공간입니다.')
'''
# 공간 화면 출력 + #pagination code
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def show_space(request, space_name):
    # 존재하는 space_name 인지 검사
    space = Space.objects.get(space_name=space_name, space_access='public')
    if space:
        # space에 들어있는 게시글 가져오기
        post_count = 5  # Show 5 contacts per page
        posts = Post.objects.filter(space_id=space.id)
        page = request.GET.get('page')
        paginator = Paginator(posts, post_count)
        page_count = range(1, paginator.num_pages + 1)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            posts = paginator.page(paginator.num_pages)
            a = []
        # for i in posts.paginator.num_pages:
        #    a.append(i)

        return render(request, 'space/show_space.html', {'space': space, 'posts': posts, 'page_count': page_count})

    return HttpResponse('존재하지 않는 공간입니다.')


from space import malware_manager
from space import graph


# 글쓰기
def write_post(request, space_name):
    if request.method == 'POST':
        form = WritePostForm(request.POST, request.FILES)

        if form.is_valid():

            # s3에 파일이 업로드 되기까지 기다리기 위해 sleep()을 사용함.
            # code smell이 매우 역하지만, 해결하기 위해 투자할 시간과 기술이 현재로써는 없다.
            time.sleep(2.5)
            check_result = -1
            if form.cleaned_data['post_file'] is not None:
                file_name = form.cleaned_data['post_file'].name
                file_path = os.path.abspath(os.path.join('awc_site/MCDM_code/S3Control_Python/' + file_name, os.pardir))
                print('---file_path : ', file_path)
                with graph.as_default():
                    # 멀웨어 검사 (멀웨어면 1, 아니면 0 반환)
                    check_result = malware_manager.malware_check_s3(space_name, file_name)

            # 공간의 기본키 가져와서 Post 모델 객체에 지정해주기
            space = Space.objects.get(space_name=space_name)
            form.space = space
            # 작성자 닉네임 가져오기
            writer = request.user.nickname
            # DB에 저장
            form.save(space=space, writer=writer, check_result=check_result)

            return HttpResponseRedirect('/space/' + space_name)

    else:
        form = WritePostForm()

    return render(request, 'space/write_post.html', {'form': form, 'space_name': space_name})


# 게시글 보기
def post_detail(request, space_name, post_id):
    # 없는 포스트라면 404페이지로 넘겨준다.
    space = Space.objects.get(space_name=space_name)
    post = get_object_or_404(Post, space_id=space.id, id=post_id)
    return render(request, 'space/post_detail.html', {'post': post, 'space': space})


def search_name(request):
    return render(request, 'space/search_name.html')


def information(request):
    return render(request, 'space/information.html')

awc_site/templates/space/create_space.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    {% extends 'base.html' %}
    <title>공간 생성</title>
    <META http-equiv=”Expires” content=”-1″>
    <META http-equiv=”Pragma” content=”no-cache”>
    <META http-equiv=”Cache-Control” content=”No-Cache”>
</head>
<body>
{% block content %}
    <div class="container" style="outline-color: black">
        <h2>공간 생성</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ create_space_form.as_p }}
            <input type="submit" name="" value="확인" onclick = createBoard(document.getElementById("id_space_name").value.toString())>
        </form>
    </div>
{% endblock %}

</body>
</html>

awc_site/templates/space/create_space_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends 'base.html' %}
    <title>{% block title %} -Done{% endblock %}</title>
</head>
<body>
{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <div class="alert alert-info">
            공간 생성 완료.<br/>
            공간 링크 : <a href="/space/{{space_name}}"> 127.0.0.1:8000/space/{{space_name}}</a>
        </div>
        <a class="btn btn-info" href="/">Move to main</a>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}
</body>
</html>

awc_site/templates/space/information.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'search_base.html' %}
    <title> {% block title %}{% endblock %}</title>

    {% load static %}


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
{% block content%}
    <style>
        .border {
            display: inline-block;
            margin: 6px;

        }
    </style>

    <div class="container"><span class="border border-secondary">
        <div class="row">

            <div class="col-md-3">

                <br><br>
                <p style="text-align: center;">
                    <img src="{% static 'main/privacy.png' %}" alt="">
                </p>
                <p>
                    비밀번호, 파일과 같은 중요 정보들은 암호화되어 저장됩니다.
                </p>
            </div>

            <div class="col-md-3">
                <br><br>
                <p style="text-align: center;">
                    <img src="{% static 'main/robot.png' %}" alt="">
                </p>
                <p>
                    첨부파일은 인공지능이 안전성 검사를 통과해야만 공유가 가능합니다!
                </p>
            </div>
            <div class="col-md-3">
                <br><br>
                <p style="text-align: center;">
                    <img src="{% static 'main/locked-padlock.png' %}" alt="">
                </p>
                <p>
                    링크 하나로 쉽게 커뮤니티 공간에 입장할 수 있습니다.
                </p>
            </div>
            <div class="col-md-3">
                <br><br>
                <p style="text-align: center;">
                    <img src="{% static 'main/qr.png' %}" alt="">
                </p>
                <p>
                    더 자세한 정보는 QR 코드를 참조해주세요!
                </p>
            </div>


        </div> </span>
    </div>
{% endblock %}

</body>
</html>

awc_site/templates/space/post_detail.html
{% extends 'base.html' %}

{% block content %}
<style>
        table {
            border-collapse: collapse;
            text-align: left;
            line-height: 1.5;
        }
        table thead th {
            padding: 10px;
            font-weight: bold;
            vertical-align: top;
            color: #369;
            border-bottom: 3px solid #036;
        }
        table tbody th {
            width: 150px;
            padding: 10px;
            font-weight: bold;
            vertical-align: top;
            border-bottom: 1px solid #ccc;
            background: #f3f6f7;
        }
        table td {
            width: 350px;
            padding: 10px;
            vertical-align: top;
            border-bottom: 1px solid #ccc;
        }
        table.table thead th {
            padding: 10px;
            font-weight: bold;
            vertical-align: top;
            color: #369;
            border-bottom: 3px solid #036;
        }
        table.table td {
            width: 350px;
            padding: 10px;
            vertical-align: top;
            border-bottom: 1px solid #ccc;
        }

    </style>
<div class="container" style="outline-color: black">

    <h5 hidden id="boardname">{{ space.space_name }}</h5>
    <h5 hidden id="filename">{{ post.post_file }}</h5>
</div>

<div class="row">
    <div class="container">
        <div class="col-md-12 panel panel-default">
            <div class="alert alert-info">다운로드를 원하시면 클릭하세요!<br>
            </div>
        </div>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>제목</th>
                <th>작성날짜</th>
                <th>다운로드</th>
                <th>파일 검사결과</th>
            </tr>
            </thead>
            <tbody id="myTable">
            <tr>
                <td>
                    <a >{{ post.post_title }}</a>
                </td>
                <td>{{ post.post_date }}</td>
                <td> <div class="download">
                    {% if post.post_file %}
                    {{ post.post_file }}
                    <input type="submit" id="downloadfile" value="다운로드"
                           onclick=downloadObject(document.getElementById('boardname').innerHTML,document.getElementById('filename').innerHTML)>
                    {% else %}
                    <p>첨부파일 없음</p>
                    {%endif%}

                </div></td>
                <td id="malware_result">{{ post.malware_result }}</td>
            </tr>
            <td colspan="4">
                {{ post.post_contents|safe }}
            </td>
            </tbody>
        </table>
    </div>
    <script>
        malware = document.getElementById("malware_result").innerHTML;
        if(malware == -1 ) malware = "결과없음";
        else if(malware == 0) malware = "안전";
        else if(malware == 1) malware = "위험";
        document.getElementById("malware_result").innerHTML = malware;
    </script>
</div>
{% endblock %}

awc_site/templates/space/search_name.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'search_base.html' %}
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <title>테스트용 서치 폼</title>
</head>
<body>
{% block content%}
<div class="container">
    <form action="{% url 'space:search_space_list' %}" method="get">
    <select name="search_option">
        <option value="space_name">공간이름으로 검색</option>
        <option value="space_category">공간 카테고리로 검색</option>
    </select>
    <input type="text" name="q" value="{{ q }}">
    <input type="submit" value="공간 검색">
</form>
</div>
{% endblock %}
</body>
</html>

awc_site/templates/space/show_space.bak.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    {% extends 'base.html' %}
    <title>{{ space.space_name }}</title>
</head>
<body>
{% block content %}
<h2>공간 이름 : {{ space.space_name }}</h2>
<p>공간 카테고리 : {{ space.space_category }}</p>
{% if posts %}
<table width="500px" height="200px">
    <tr>
        <th>글제목</th>
        <th>작성자</th>
        <th>첨부파일 유무</th>
        <th>파일검사 유무</th>
    </tr>
    {% for post in posts %}
    <tr>
        <td >
            <a href="{% url 'space:post_detail' space_name=space.space_name post_id=post.id %}">{{ post.post_title }}</a>
        </td>
        <td>{{ post.writer }}</td>
        <td>
            {% if post.post_file %}
            <p>O</p>
            {% else %}
            <p>X</p>
            {% endif %}
        </td>
        <td>{{ post.malware_result }}</td>
    </tr>

    {% endfor %}
</table>

{% else %}
<p>등록된 게시글이 없습니다.</p>
{% endif %}
{% if user.is_authenticated %}
<a href="{% url 'space:write_post' space_name=space.space_name %}" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-pencil"></span> 글쓰기</a>
{% endif %}

{% endblock %}
</body>
</html>

awc_site/templates/space/show_space.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    {% extends 'accounts/../base.html' %}
    <title>{{ space.space_name }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
<style>
        table {
            border-collapse: collapse;
            text-align: left;
            line-height: 1.5;
        }
        table thead th {
            padding: 10px;
            font-weight: bold;
            vertical-align: top;
            color: #369;
            border-bottom: 3px solid #036;
        }
        table tbody th {
            width: 150px;
            padding: 10px;
            font-weight: bold;
            vertical-align: top;
            border-bottom: 1px solid #ccc;
            background: #f3f6f7;
        }
        table td {
            width: 350px;
            padding: 10px;
            vertical-align: top;
            border-bottom: 1px solid #ccc;
        }
        table.table thead th {
            padding: 10px;
            font-weight: bold;
            vertical-align: top;
            color: #369;
            border-bottom: 3px solid #036;
        }
        table.table td {
            width: 350px;
            padding: 10px;
            vertical-align: top;
            border-bottom: 1px solid #ccc;
        }

    </style>
<script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
<div class="row">
    <div class="container">
        <div class="col-md-12 panel panel-default">
            <div class="alert alert-info">{{ space.space_name }}에 오신걸 환영합니다.<br>
                "{{ space.space_category }}" 카테고리에 대한 페이지입니다.
            </div>

        </div>
        <h2>필터링 검색</h2>
        {% if posts %}
        <input class="form-control" id="myInput" type="text" placeholder="Search..">
        <br><br>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>글제목</th>
                    <th>작성자</th>
                </tr>
                </thead>
                <tbody id="myTable">
                {% for post in posts %}
                <tr>
                    <td><a href="{% url 'space:post_detail' space_name=space.space_name post_id=post.id %}">{{ post.post_title }}</a></td>
                    <td>{{ post.writer }}</td>

                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p>등록된 게시글이 없습니다.</p>
        {% endif %}
        {% if user.is_authenticated %}
        <a href="{% url 'space:write_post' space_name=space.space_name %}" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-pencil"></span>새로운 글 추가하기 </a>
        {% endif %}
        <ul class="pagination justify-content-center">
            {% if posts.has_previous %}
            <li class ="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}"  style="color:Black"> 이전 </a></li>
            {% else %}
            <li class ="page-item"><a class="page-link" href="#" style="color:Black"> 이전 </a></li>
            {% endif %}

            {% for i in page_count %}
            {% if i == posts.number %}
            <li class="page-item"><a class="page-link" href="#" style="color:Black">{{ i }} </a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }} </a></li>
            {% endif %}
            {% endfor %}

            {% if posts.has_next %}
            <li class ="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}" style="color:Black"> 다음 </a></li>
            {% else %}
            <li class ="page-item"><a class="page-link" href="#" style="color:Black"> 다음 </a></li>
            {% endif %}
        </ul>
    </div>

</div>


{% endblock %}
</body>
</html>

awc_site/templates/space/write_post.html
{% extends 'base.html' %}
{% block title %}글쓰기{% endblock %}
{% block content %}
    <h5 hidden id="space_name">{{ space_name }}</h5>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <div class="alert alert-info">글 쓰기와 파일첨부</div>
            <div class="container">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_ul}}
                    <!-- spacename부분에 현재 위치한 공간 이름을 넣어야 해  -->
                    <button type="submit" class="btn btn-info btn-lg" onclick = uploadObject(document.getElementById('space_name').innerHTML)>확인</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}
{% comment %}<p>{{ user.nickname }}</p>{% endcomment %}
</body>
</html>